version: "3.4"
services:
  mongodb:
    network_mode: host
    container_name: mongodb
    ports:
      - "27017-27019:27017-27019"
    image: mongo:latest
    volumes:
      - ~/mongo-volume: /data/db
  cv:
    build: .
    container_name: cv
    ports:
      - 8080:8080
    volumes:
      - ./:/home/app
    command:
      [ "node", "./server/server.js" ]
    depends_on:
      - mongodb
