version: "3.4"
services:
  mongodb:
    #network_mode: host
    #environment:
      # change the following username and password
      #- MONGO_INITDB_ROOT_USERNAME=username
      #- MONGO_INITDB_ROOT_PASSWORD=password
    container_name: mongodb
    ports:
      - "27017-27019:27017-27019"
    image: mongo:latest
    #command: mongod
  cv:
    build: .
    container_name: cv
    ports:
      - 8080:8080
    volumes:
      - ./:/home/app
    command:
      [ "node", "./server/server.js" ]
    depends_on:
      - mongodb
